[colors.cursor]
cursor = "#77bdfb"
text = "CellBackground"

[colors.search.focused_match]
background = "#cea5fb"
foreground = "#000000"

[colors.search.matches]
background = "#7ce38b"
foreground = "#000000"

[colors.vi_mode_cursor]
cursor = "#a2d2fb"
text = "#161b22"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = " "
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mods = "Command"

[mouse]
hide_when_typing = false

[window]
decorations = "full"
dynamic_title = false
opacity = 0.975
option_as_alt = "None"
title = "Terminal"

[window.dimensions]
columns = 256
lines = 75

[window.padding]
x = 5
y = 5

[window.position]
x = 600
y = 0
